/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class universeCore_nativeImpl_FieldHandlerImpl */

#ifndef _Included_universeCore_nativeImpl_FieldHandlerImpl
#define _Included_universeCore_nativeImpl_FieldHandlerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setInt
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setInt
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setFloat
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;F)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setFloat
  (JNIEnv *, jclass, jobject, jobject, jfloat);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setBoolean
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setBoolean
  (JNIEnv *, jclass, jobject, jobject, jboolean);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setLong
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;J)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setLong
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setDouble
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;D)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setDouble
  (JNIEnv *, jclass, jobject, jobject, jdouble);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setShort
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;S)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setShort
  (JNIEnv *, jclass, jobject, jobject, jshort);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setByte
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;B)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setByte
  (JNIEnv *, jclass, jobject, jobject, jbyte);

/*
 * Class:     universeCore_nativeImpl_FieldHandlerImpl
 * Method:    setObject
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_universeCore_nativeImpl_FieldHandlerImpl_setObject
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
